refactor init

diff --git a/bin/run b/bin/run
--- a/bin/run
+++ b/bin/run
@@ -1,111 +1,124 @@
 #!/bin/bash
 
 set -e
-
-[ -d /dev/net ] ||
-  mkdir -p /dev/net
-[[ -c /dev/net/tun ]] ||
-  mknod /dev/net/tun c 10 200
-
 cd /etc/openvpn
 
-[ -f dh.pem ] ||
-  openssl dhparam -out dh.pem 2048
-[ -f key.pem ] ||
-  openssl genrsa -out key.pem 2048
-[ -f csr.pem ] ||
-  openssl req -new -key key.pem -out csr.pem -subj /CN=OpenVPN/
-[ -f cert.pem ] ||
-  openssl x509 -req -in csr.pem -out cert.pem -signkey key.pem -days 36525
+function do_init() {
+	[ -d /dev/net ] ||
+		mkdir -p /dev/net
+	[[ -c /dev/net/tun ]] ||
+		mknod /dev/net/tun c 10 200
 
-[ -f tcp443.conf ] || cat >tcp443.conf <<EOF
-server 5.5.0.0 255.255.0.0
-verb 3
-duplicate-cn
-key /etc/openvpn/key.pem
-ca /etc/openvpn/cert.pem
-cert /etc/openvpn/cert.pem
-dh /etc/openvpn/dh.pem
-keepalive 10 60
-persist-key
-persist-tun
-
-proto tcp-server
-port 443
-dev tun443
-status openvpn-status-443.log
-
-tls-version-min 1.2
-EOF
-
-[ -f udp1194.conf ] || cat >udp1194.conf <<EOF
-server 5.5.0.0 255.255.0.0
-verb 3 duplicate-cn
-key /etc/openvpn/key.pem
-ca /etc/openvpn/cert.pem
-cert /etc/openvpn/cert.pem
-dh /etc/openvpn/dh.pem
-keepalive 10 60
-persist-key
-persist-tun
-
-proto udp
-port 1194
-dev tun1194
-status openvpn-status-1194.log
-
-tls-version-min 1.2
-EOF
-
-MY_IP_ADDR=$(curl -s http://myip.enix.org/REMOTE_ADDR)
-[ "$MY_IP_ADDR" ] || {
-    echo "Sorry, I could not figure out my public IP address."
-    echo "(I use http://myip.enix.org/REMOTE_ADDR/ for that purpose.)"
-    exit 1
+	iptables -t nat -A POSTROUTING -s  5.5.0.0/16 -o eth0 -j MASQUERADE
 }
 
-[ -f client.ovpn ] || cat >client.ovpn <<EOF
-client
-nobind
-dev tun
-redirect-gateway def1
+function gen_server_config() {
+	[ -f dh.pem ] ||
+		openssl dhparam -out dh.pem 2048
+	[ -f key.pem ] ||
+		openssl genrsa -out key.pem 2048
+	[ -f csr.pem ] ||
+		openssl req -new -key key.pem -out csr.pem -subj /CN=OpenVPN/
+	[ -f cert.pem ] ||
+		openssl x509 -req -in csr.pem -out cert.pem -signkey key.pem -days 36525
 
-<key>
-`cat key.pem`
-</key>
-<cert>
-`cat cert.pem`
-</cert>
-<ca>
-`cat cert.pem`
-</ca>
-<dh>
-`cat dh.pem`
-</dh>
+	[ -f tcp443.conf ] || cat >tcp443.conf <<-EOF
+		server 5.5.0.0 255.255.0.0
+		verb 3
+		duplicate-cn
+		key /etc/openvpn/key.pem
+		ca /etc/openvpn/cert.pem
+		cert /etc/openvpn/cert.pem
+		dh /etc/openvpn/dh.pem
+		keepalive 10 60
+		persist-key
+		persist-tun
 
-<connection>
-remote $MY_IP_ADDR 1194 udp
-</connection>
+		proto tcp-server
+		port 443
+		dev tun443
+		status openvpn-status-443.log
 
-<connection>
-remote $MY_IP_ADDR 443 tcp-client
-</connection>
-EOF
+		tls-version-min 1.2
+	EOF
 
-iptables -t nat -A POSTROUTING -s  5.5.0.0/16 -o eth0 -j MASQUERADE
+	[ -f udp1194.conf ] || cat >udp1194.conf <<-EOF
+		server 5.5.0.0 255.255.0.0
+		verb 3 duplicate-cn
+		key /etc/openvpn/key.pem
+		ca /etc/openvpn/cert.pem
+		cert /etc/openvpn/cert.pem
+		dh /etc/openvpn/dh.pem
+		keepalive 10 60
+		persist-key
+		persist-tun
+
+		proto udp
+		port 1194
+		dev tun1194
+		status openvpn-status-1194.log
+
+		tls-version-min 1.2
+	EOF
+}
+
+
+function gen_client_config() {
+	MY_IP_ADDR=$(curl -s http://myip.enix.org/REMOTE_ADDR)
+	[ "$MY_IP_ADDR" ] || {
+			echo "Sorry, I could not figure out my public IP address."
+			echo "(I use http://myip.enix.org/REMOTE_ADDR/ for that purpose.)"
+			exit 1
+	}
+
+	cat <<-EOF
+		client
+		nobind
+		dev tun
+		redirect-gateway def1
+
+		<key>
+		`cat key.pem`
+		</key>
+		<cert>
+		`cat cert.pem`
+		</cert>
+		<ca>
+		`cat cert.pem`
+		</ca>
+		<dh>
+		`cat dh.pem`
+		</dh>
+
+		<connection>
+		remote $MY_IP_ADDR 1194 udp
+		</connection>
+
+		<connection>
+		remote $MY_IP_ADDR 443 tcp-client
+		</connection>
+	EOF
+}
+
 
 case $1 in
-  --udp)
-     exec openvpn udp1194.conf
-    ;;
-  --tcp)
-     exec openvpn tcp443.conf
-    ;;
-  --config)
-    cat client.ovpn
-    ;;
-  *)
-    echo "No option specified, using UDP config"
-    exec openvpn udp1194.conf
-    ;;
+	--udp)
+		do_init
+		gen_server_config
+		exec openvpn udp1194.conf
+		;;
+	--tcp)
+		do_init
+		gen_server_config
+		exec openvpn tcp443.conf
+		;;
+	--config)
+		gen_client_config
+		;;
+	*)
+		echo "No option specified, using UDP config"
+		do_init
+		gen_server_config
+		exec openvpn udp1194.conf
+		;;
 esac
